version: "3.8"

services:

  gotenberg:
    image: gotenberg/gotenberg:8
    container_name: gotenberg
    ports:
      - "${GOTENBERG_PORT}"
    command:
      - "gotenberg"
      - "--chromium-disable-routes=false"
      - "--libreoffice-disable-routes=false"
      - "--pdfengines-disable-routes=false"
    restart: unless-stopped

  localstack:
    image: localstack/localstack:3
    container_name: localstack
    ports:
      - "${LOCALSTACK_PORT}"
    environment:
      - SERVICES=s3
      - AWS_DEFAULT_REGION=${AWS_REGION}
      - EAGER_SERVICE_LOADING=1
    volumes:
      - "./init-s3.sh:/etc/localstack/init/ready.d/init-s3.sh"
    restart: unless-stopped

  pdf-generator:
    build: .
    container_name: pdf-generator
    ports:
      - "${APP_PORT}:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - GOTENBERG_BASE_URL=${GOTENBERG_BASE_URL}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - AWS_S3_ENDPOINT=${AWS_S3_ENDPOINT}
    depends_on:
      - gotenberg
      - localstack
    restart: unless-stopped
