server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  jackson:
    default-property-inclusion: non_null

gotenberg:
  base-url: ${GOTENBERG_BASE_URL}
  timeout-seconds: 30

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket-name: ${S3_BUCKET_NAME}
    presign-expiration-minutes: ${S3_PRESIGN_EXPIRATION_MINUTES}
    endpoint: ${AWS_S3_ENDPOINT}

logging:
  level:
    com.techpulse.pdfservice: DEBUG
