gotenberg:
  base-url: ${GOTENBERG_BASE_URL}
  timeout-seconds: 60

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ${AWS_REGION}
    bucket-name: ${S3_BUCKET_NAME}
    presign-expiration-minutes: ${S3_PRESIGN_EXPIRATION_MINUTES}

logging:
  level:
    com.techpulse.pdfservice: INFO
    com.amazonaws: WARN
